name: Build and Deploy Staging

on:
  push:
    branches:
      - "staging"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vzauartcc/roster-sync
  K8_NAMESPACE: zau-staging-web-stack
  DEPLOYMENT_NAME: roster-sync-dev

jobs:
  Build-and-Push-to-GHCR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4

      - name: Log in to container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  Deploy-to-Staging:
    needs: Build-and-Push-to-GHCR
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Initialize doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log into K8s cluster
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 zau-k8s

      - name: Deploy image to cluster
        run: kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --record -n ${{ env.K8_NAMESPACE }}

      - name: Verify deployment
        run: kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.K8_NAMESPACE }}
