name: Build and Deploy Staging

on:
  push:
    branches:
      - "staging"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vzauartcc/roster-sync
  K8_NAMESPACE: zau-staging-web-stack
  DEPLOYMENT_NAME: roster-sync-dev

jobs:
  Build-and-Push-to-GHCR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Log in to container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  Deploy-to-Staging:
    needs: Build-and-Push-to-GHCR
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Initialize doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log into K8s cluster
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 zau-k8s

      - name: Deploy image to cluster
        run: kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --record -n ${{ env.K8_NAMESPACE }}

      - name: Verify deployment
        run: kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.K8_NAMESPACE }}
