# Make sure to enable 'Require status checks to pass before merging' on the branch protection,
# and to select the 'go-tidy-check' action.

name: Go Tidy Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  go-tidy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"

      - name: Run go mod tidy
        run: go mod tidy

        # If 'go mod tidy' changed anything, git status will be dirty, and this command exits with code 1
      - name: Check for changes
        run: git diff --exit-code go.mod go.sum
