# Make sure to enable 'Require status checks to pass before merging' on the branch protection,
# and to select the 'gofmt_check' action.

name: Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

permissions: {}

jobs:
  gofmt_check:
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]'

    steps:
      - name: Checkout main
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"

      - name: Run go fmt
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "The following files are not formatted correctly:"
            go fmt ./...
            exit 1
          fi
