# Make sure to enable 'Require status checks to pass before merging' on the branch protection,
# and to select the 'gofmt_check' action.

name: Prettier Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  gofmt_check:
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]'

    steps:
      - name: Checkout main
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"

      - name: Run go fmt
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "The following files are not formatted correctly:"
            go fmt ./...
            exit 1
          fi
