# Make sure to enable 'Require status checks to pass before merging' on the branch protection,
# and to select the 'golangci-lint' action.

name: Lint
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

permissions: {}

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          version: v2.11.4
          only-new-issues: true
