# Make sure to enable 'Require status checks to pass before merging' on the branch protection,
# and to select the 'CI Check' action.

name: CI Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

permissions: {}

jobs:
  Verify-App-Builds-and-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: go mod download

      - name: Verify Dependencies
        run: go mod verify

      - name: Build App
        run: go build -v ./...

      - name: Run Tests
        run: go test -v -race -cover ./...
